# Generated by Django 4.2.5 on 2023-09-15 05:54

import albumApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albumApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.png', null=True, upload_to=albumApp.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.png', null=True, upload_to=albumApp.models.user_directory_path),
        ),
    ]
